# Site settings
title: Bike Index - List of Stolen Bikes
email: info@brownborgstudios.com
description: "Test page for creating a list of all stolen bikes."
baseurl: "http://andrewborstein.github.io/"
url: "http://github.com/andrewborstein"

# Build settings
markdown: kramdown
permalink: pretty
